version: '3.19'

services:
  api:
    build:
      dockerfile: ./back/Dockerfile
    ports:
      - "3333:3333"
    networks:
      - internal
  # depends_on:
  #   - mysql_db
  # volumes:
  #   - /app/node_modules
  #   - ./server:/app
  # environment:
  #   <<: *common-variables
  #   MYSQL_HOST_IP: mysql_db

networks:
  internal:
  driver: bridge
